# -*-Makefile-*-

TEX := extras \
       beamer_cfg.tex \
       h2_mapping.tex single-node.tex xor.tex \
       hidden_layer_mapping.tex thresholds_xor.tex \
       four_layers.tex incomplete_xor.tex xor_conf.tex \
       h1_mapping.tex output_layer_mapping.tex xor_opp_biases.tex

BIB = extras
ORIENT := landscape
